### ISSUE TITLE
How to update code to allow certain cors origins like localhost

### ISSUE THREAD

**Issue by ichala** [axsddlr/lost_ark_api#1]

**Comment by ichala** [comment]
#Add this below app = FastAPI()
origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

**Comment by axsddlr** [comment]
> #Add this below app = FastAPI() origins = ["*"]
> 
> app.add_middleware( CORSMiddleware, allow_origins=origins, allow_credentials=False, allow_methods=["_"], allow_headers=["_"], )

https://github.com/axsddlr/lost_ark_api/commit/30b918e3199044db870491807c8a22b17784f462
