### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by zalimitless** [axsddlr/lost_ark_api#2]
This API is just what I needed!
However, please update the Readme file on what we can expect when we run this application.

- Requirements and how to install them.
- RestAPI server running. (0.0.0.0:3000)
- What are some of the API endpoints? (Server Status, News, Forums)

I am writing this request, as I saw this API at least 3 times before deciding to see if it is what I wanted.

**Comment by axsddlr** [comment]
http://lostarkapi.herokuapp.com/ has the list of endpoints and interface to try out endpoints.

running localhost since its designed to run on heroku or docker.

repo was designed to just open source the backend of http://lostarkapi.herokuapp.com/

**Comment by zalimitless** [comment]
Maybe just add that into the readme file for clarification.

**Comment by zalimitless** [comment]
I could also make a PR of a potential README.md file.

The idea is just to tell people what is going on in the project when they first see it.

**Comment by axsddlr** [comment]
submit a PR if you want more information in readme. Again this repo is for Open Source purpose. If people want to run it, its easily done as is
