### ISSUE TITLE
Frequent 500 Errors

### ISSUE THREAD

**Issue by lilmayu** [axsddlr/lost_ark_api#5]
Hi,
I've been using this API for a few days and I've noticed that every day more than a few times the vercel app crashed and herokuapp app was not running. 

> ![obrazek](https://user-images.githubusercontent.com/52459400/161308978-7199267f-a650-4950-94b7-53aea560f34e.png)
> https://lost-ark-api.vercel.app/
> And with herokuapp, if a 500 error occurs, API responds with plaintext "Internal Server Error".

Just making sure, you know this is happening since I haven't seen any issue relating to this.

**Comment by axsddlr** [comment]
https://lost-ark-api.vercel.app/ working for me fine but bother vercel and heroku are free options. I have a vps but i refuse to use it to host this api as it will absorb all the bandwidth im allowed. only other options is if i change api to pay option or get donated a vps

**Comment by lilmayu** [comment]
Yes, it is working fine right now. However, there could be some problem within the code that is causing the 500 errors, I suppose.

**Comment by axsddlr** [comment]
> Yes, it is working fine right now. However, there could be some problem within the code that is causing the 500 errors, I suppose.

nothing wrong with the code as i run it on my own vps server with 0 issues, likely the services. Code also checks if site is down and itll post a text statement if it is
